# Generated by Django 2.0.2 on 2018-02-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmify', '0004_lead_external_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sync_hash',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
